"""
Rare problem selection and problem-family generation for the
"Single-Problem Generalization" experiment.

A problem is "rare" if:
  1. Pass@16 ≈ 0 on the base model (unsolved)
  2. High embedding distance from all training problems (unseen)

A problem family F(x_r) = {x_r^(1), ..., x_r^(m)} preserves the
underlying reasoning structure but varies numbers, surface form, and framing.
Generated by the teacher model.
"""

import json
from pathlib import Path
from typing import Optional

import numpy as np

from generation.rollout import extract_answer

RARE_CACHE = Path(__file__).parent.parent / "results" / "rare_problem_cache"

FAMILY_PROMPT = """\
You are a competition math problem designer.

Here is a math problem:
{problem}

Its correct answer is: {answer}

Generate {m} variants of this problem that:
1. Preserve the EXACT same underlying reasoning structure and mathematical concept
2. Change the numbers, constraints, or surface framing so the answer differs
3. Are self-contained and unambiguous
4. Have a clean integer or simple fraction answer

Format exactly as:

## Variant 1
<problem statement>
Answer: <answer>

## Variant 2
<problem statement>
Answer: <answer>

(and so on)"""


def select_rare_problem(
    problems: list[dict],
    rollouts: dict[str, list[str]],
    train_embeddings: Optional[np.ndarray] = None,
    top_k: int = 5,
) -> dict:
    """
    Select the rarest problem: lowest Pass@16 AND highest distance from training set.

    Args:
        problems: list of {id, problem, answer}
        rollouts: problem_id -> list of rollouts (already generated on base model)
        train_embeddings: (N, D) embeddings of training problems; if None, skip distance filter
        top_k: number of candidates to return (returns the hardest one)

    Returns:
        The selected rare problem dict (with added 'pass_at_16' and 'train_distance' fields)
    """
    from evaluation.compute_rdiv import embed_text, _get_embedder

    answer_map = {p["id"]: p["answer"] for p in problems}

    # Compute Pass@16 for each problem
    scored = []
    for p in problems:
        rolls = rollouts.get(p["id"], [])
        if not rolls:
            continue
        gold = answer_map[p["id"]]
        n_correct = sum(extract_answer(r) == gold for r in rolls)
        pass16 = n_correct / len(rolls)
        scored.append({**p, "pass_at_16": pass16})

    # Filter to truly unsolved (Pass@16 == 0)
    unsolved = [p for p in scored if p["pass_at_16"] == 0.0]
    if not unsolved:
        # Relax: take bottom 10%
        unsolved = sorted(scored, key=lambda x: x["pass_at_16"])[:max(1, len(scored) // 10)]

    if train_embeddings is None or len(unsolved) == 1:
        # Just pick the one with lowest pass rate; break ties arbitrarily
        return sorted(unsolved, key=lambda x: x["pass_at_16"])[0]

    # Among unsolved, pick the one farthest from training distribution
    embedder = _get_embedder()
    candidates = []
    for p in unsolved:
        emb = embed_text(p["problem"], embedder)
        # Min cosine similarity to any training problem
        sims = np.dot(train_embeddings, emb)
        min_dist = 1.0 - float(np.max(sims))
        candidates.append({**p, "train_distance": min_dist})

    # Sort by distance descending (farthest = most unseen)
    candidates.sort(key=lambda x: x["train_distance"], reverse=True)
    selected = candidates[0]
    print(
        f"[rare] Selected: id={selected['id']} "
        f"pass@16={selected['pass_at_16']:.3f} "
        f"train_dist={selected.get('train_distance', 'N/A'):.3f}"
    )
    return selected


def generate_problem_family(
    problem: dict,
    m: int = 5,
    api_key: Optional[str] = None,
    api_base: Optional[str] = None,
    model: str = "deepseek/deepseek-r1-distill-qwen-32b",
) -> list[dict]:
    """
    Generate m variants of a rare problem using the teacher model.
    Returns list of {problem, answer, source} dicts.
    Caches results to disk.
    """
    import asyncio
    from generation.pas_augment import _make_client

    RARE_CACHE.mkdir(parents=True, exist_ok=True)
    cache_path = RARE_CACHE / f"{problem['id']}_family.json"

    if cache_path.exists():
        with open(cache_path) as f:
            cached = json.load(f)
        print(f"[rare] Loaded {len(cached)} variants from cache")
        return cached

    async def _gen():
        client = _make_client(api_key, api_base)
        prompt = FAMILY_PROMPT.format(
            problem=problem["problem"],
            answer=problem["answer"],
            m=m,
        )
        for attempt in range(3):
            try:
                resp = await client.chat.completions.create(
                    model=model,
                    messages=[{"role": "user", "content": prompt}],
                    temperature=0.7,
                    max_tokens=3000,
                )
                return resp.choices[0].message.content
            except Exception as e:
                if attempt == 2:
                    raise
                import asyncio as _a
                await _a.sleep(2 ** attempt)

    raw = asyncio.run(_gen())
    variants = _parse_family(raw, m)

    with open(cache_path, "w") as f:
        json.dump(variants, f, indent=2)

    print(f"[rare] Generated {len(variants)} variants for {problem['id']}")
    return variants


def _parse_family(text: str, m: int) -> list[dict]:
    """Parse ## Variant N sections from teacher response."""
    import re

    variants = []
    for i in range(1, m + 1):
        start_marker = f"## Variant {i}"
        end_marker = f"## Variant {i + 1}" if i < m else None

        start = text.find(start_marker)
        if start == -1:
            continue
        start += len(start_marker)

        end = text.find(end_marker) if end_marker else len(text)
        block = text[start:end].strip()

        # Extract answer from "Answer: X" line
        ans_match = re.search(r"Answer:\s*(.+)", block, re.IGNORECASE)
        answer = ans_match.group(1).strip() if ans_match else ""

        # Problem text is everything before the Answer line
        problem_text = re.sub(r"\nAnswer:.*", "", block, flags=re.IGNORECASE).strip()

        if problem_text:
            variants.append({
                "id": f"variant_{i}",
                "problem": problem_text,
                "answer": answer,
                "source": "variant",
            })

    return variants


def build_rare_experiment_dataset(
    base_problems: list[dict],
    rare_problem: dict,
    strategy: str,
    k: int = 3,
    api_key: Optional[str] = None,
) -> list[dict]:
    """
    Build training dataset for rare-problem generalization experiment.

    strategy: "sft_rare" (1 sol), "multi_sft_rare" (k sols), "pas_rare" (PAS)
    Token budget is kept ~equal across conditions by controlling k.

    Returns list of training rows (same format as build_sft_dataset).
    """
    from generation.build_sft_dataset import _make_row, load_math_train
    from generation.pas_augment import PASAugmenter

    experiment_id = f"{strategy}_generalization"
    rows = []

    # Full training set (same for all 3 conditions)
    for p in base_problems:
        rows.append(_make_row(p["problem"], p["solution"], p["id"], "original", experiment_id))

    if strategy == "sft_rare":
        # Add 1 solution for rare problem
        rows.append(_make_row(
            rare_problem["problem"], rare_problem["solution"],
            rare_problem["id"], "rare_original", experiment_id
        ))

    elif strategy == "multi_sft_rare":
        # Add k copies of same solution (token-matched to PAS condition)
        # In practice: use PAS alternatives but label as "multi_sft" for ablation
        # We use teacher-generated alts but WITHOUT diversity — just repeat
        augmenter = PASAugmenter(api_key=api_key)
        augmented = augmenter.augment_dataset(
            [rare_problem], k=k - 1, context_mode="full",
            experiment_id=f"multi_sft_rare_k{k}", include_original=True
        )
        for p in augmented:
            rows.append(_make_row(
                p["problem"], p["solution"], p["id"],
                f"rare_{p['source']}", experiment_id
            ))

    elif strategy == "pas_rare":
        # Full PAS augmentation on rare problem
        augmenter = PASAugmenter(api_key=api_key)
        augmented = augmenter.augment_dataset(
            [rare_problem], k=k, context_mode="full",
            experiment_id="pas_rare_full", include_original=True
        )
        for p in augmented:
            rows.append(_make_row(
                p["problem"], p["solution"], p["id"],
                f"rare_{p['source']}", experiment_id
            ))

    return rows
